modLoader = "javafml"
loaderVersion = "[47,)"
modURL = "https://modrinth.com/mod/mining-quakes"
issueTrackerURL = "https://github.com/Gauraaaaaaaa/MiningQuakes/issues"
license = "GPL-3.0"

[[mods]]
modId = "mining_quakes"
version = "${version}"
displayName = "Mining Quakes"
authors = "Gaura"
description = '''Adds shakes to blocks when destroying!'''
logoFile = "assets/mining_quakes/icon.png"

[[dependencies.mining_quakes]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.mining_quakes]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "CLIENT"
