modLoader = "javafml"
loaderVersion = "[2,)"
modURL = "https://modrinth.com/mod/mining_and_placing_animations"
issueTrackerURL = "https://github.com/Gauraaaaaaaa/MiningAndPlacingAnimations/issues"
license = "GNU GPL 3.0"

[[mods]]
modId = "mining_and_placing_animations"
version = "${version}"
displayName = "Mining & Placing Animations"
authors = "Gaura"
description = '''Adds customizable animations to blocks when mining and placing! (Mining Quakes successor)'''
logoFile = "assets/mining_and_placing_animations/icon.png"

[[dependencies.mining_and_placing_animations]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.mining_and_placing_animations]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.9,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "mining_and_placing_animations.mixins.json"
[[mixins]]
config = "mining_and_placing_animations_neoforge.mixins.json"
